//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Daroo", "Daroo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DaroKhane.DataAccess.Daroo), "AghlameNoskhe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DaroKhane.DataAccess.AghlameNoskhe), true)]
[assembly: EdmRelationshipAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Noskhe", "Noskhe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DaroKhane.DataAccess.Noskhe), "AghlameNoskhe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DaroKhane.DataAccess.AghlameNoskhe), true)]
[assembly: EdmRelationshipAttribute("DaroKhaneModel", "FK_Noskhe_Bimar", "Bimar", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DaroKhane.DataAccess.Bimar), "Noskhe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DaroKhane.DataAccess.Noskhe), true)]
[assembly: EdmRelationshipAttribute("DaroKhaneModel", "FK_Noskhe_Bimeh", "Bimeh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DaroKhane.DataAccess.Bimeh), "Noskhe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DaroKhane.DataAccess.Noskhe), true)]

#endregion

namespace DaroKhane.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DaroKhaneEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DaroKhaneEntities1 object using the connection string found in the 'DaroKhaneEntities1' section of the application configuration file.
        /// </summary>
        public DaroKhaneEntities() : base("name=DaroKhaneEntities1", "DaroKhaneEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DaroKhaneEntities1 object.
        /// </summary>
        public DaroKhaneEntities(string connectionString) : base(connectionString, "DaroKhaneEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DaroKhaneEntities1 object.
        /// </summary>
        public DaroKhaneEntities(EntityConnection connection) : base(connection, "DaroKhaneEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AghlameNoskhe> AghlameNoskhe
        {
            get
            {
                if ((_AghlameNoskhe == null))
                {
                    _AghlameNoskhe = base.CreateObjectSet<AghlameNoskhe>("AghlameNoskhe");
                }
                return _AghlameNoskhe;
            }
        }
        private ObjectSet<AghlameNoskhe> _AghlameNoskhe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bimar> Bimar
        {
            get
            {
                if ((_Bimar == null))
                {
                    _Bimar = base.CreateObjectSet<Bimar>("Bimar");
                }
                return _Bimar;
            }
        }
        private ObjectSet<Bimar> _Bimar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bimeh> Bimeh
        {
            get
            {
                if ((_Bimeh == null))
                {
                    _Bimeh = base.CreateObjectSet<Bimeh>("Bimeh");
                }
                return _Bimeh;
            }
        }
        private ObjectSet<Bimeh> _Bimeh;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Daroo> Daroo
        {
            get
            {
                if ((_Daroo == null))
                {
                    _Daroo = base.CreateObjectSet<Daroo>("Daroo");
                }
                return _Daroo;
            }
        }
        private ObjectSet<Daroo> _Daroo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Karbar> Karbar
        {
            get
            {
                if ((_Karbar == null))
                {
                    _Karbar = base.CreateObjectSet<Karbar>("Karbar");
                }
                return _Karbar;
            }
        }
        private ObjectSet<Karbar> _Karbar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Noskhe> Noskhe
        {
            get
            {
                if ((_Noskhe == null))
                {
                    _Noskhe = base.CreateObjectSet<Noskhe>("Noskhe");
                }
                return _Noskhe;
            }
        }
        private ObjectSet<Noskhe> _Noskhe;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AghlameNoskhe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAghlameNoskhe(AghlameNoskhe aghlameNoskhe)
        {
            base.AddObject("AghlameNoskhe", aghlameNoskhe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bimar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBimar(Bimar bimar)
        {
            base.AddObject("Bimar", bimar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bimeh EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBimeh(Bimeh bimeh)
        {
            base.AddObject("Bimeh", bimeh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Daroo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDaroo(Daroo daroo)
        {
            base.AddObject("Daroo", daroo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Karbar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKarbar(Karbar karbar)
        {
            base.AddObject("Karbar", karbar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Noskhe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNoskhe(Noskhe noskhe)
        {
            base.AddObject("Noskhe", noskhe);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="AghlameNoskhe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AghlameNoskhe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AghlameNoskhe object.
        /// </summary>
        /// <param name="code_noskhe">Initial value of the code_noskhe property.</param>
        /// <param name="code_daroo">Initial value of the code_daroo property.</param>
        public static AghlameNoskhe CreateAghlameNoskhe(global::System.Int32 code_noskhe, global::System.Int32 code_daroo)
        {
            AghlameNoskhe aghlameNoskhe = new AghlameNoskhe();
            aghlameNoskhe.code_noskhe = code_noskhe;
            aghlameNoskhe.code_daroo = code_daroo;
            return aghlameNoskhe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_noskhe
        {
            get
            {
                return _code_noskhe;
            }
            set
            {
                if (_code_noskhe != value)
                {
                    Oncode_noskheChanging(value);
                    ReportPropertyChanging("code_noskhe");
                    _code_noskhe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_noskhe");
                    Oncode_noskheChanged();
                }
            }
        }
        private global::System.Int32 _code_noskhe;
        partial void Oncode_noskheChanging(global::System.Int32 value);
        partial void Oncode_noskheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_daroo
        {
            get
            {
                return _code_daroo;
            }
            set
            {
                if (_code_daroo != value)
                {
                    Oncode_darooChanging(value);
                    ReportPropertyChanging("code_daroo");
                    _code_daroo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_daroo");
                    Oncode_darooChanged();
                }
            }
        }
        private global::System.Int32 _code_daroo;
        partial void Oncode_darooChanging(global::System.Int32 value);
        partial void Oncode_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tedad
        {
            get
            {
                return _tedad;
            }
            set
            {
                OntedadChanging(value);
                ReportPropertyChanging("tedad");
                _tedad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tedad");
                OntedadChanged();
            }
        }
        private Nullable<global::System.Int32> _tedad;
        partial void OntedadChanging(Nullable<global::System.Int32> value);
        partial void OntedadChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Daroo", "Daroo")]
        public Daroo Daroo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Daroo>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "Daroo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Daroo>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "Daroo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Daroo> DarooReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Daroo>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "Daroo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Daroo>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "Daroo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Noskhe", "Noskhe")]
        public Noskhe Noskhe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "Noskhe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "Noskhe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Noskhe> NoskheReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Noskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "Noskhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Noskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "Noskhe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="Bimar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bimar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bimar object.
        /// </summary>
        /// <param name="code_bimar">Initial value of the code_bimar property.</param>
        public static Bimar CreateBimar(global::System.Int32 code_bimar)
        {
            Bimar bimar = new Bimar();
            bimar.code_bimar = code_bimar;
            return bimar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_bimar
        {
            get
            {
                return _code_bimar;
            }
            set
            {
                if (_code_bimar != value)
                {
                    Oncode_bimarChanging(value);
                    ReportPropertyChanging("code_bimar");
                    _code_bimar = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_bimar");
                    Oncode_bimarChanged();
                }
            }
        }
        private global::System.Int32 _code_bimar;
        partial void Oncode_bimarChanging(global::System.Int32 value);
        partial void Oncode_bimarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_bimar
        {
            get
            {
                return _name_bimar;
            }
            set
            {
                Onname_bimarChanging(value);
                ReportPropertyChanging("name_bimar");
                _name_bimar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_bimar");
                Onname_bimarChanged();
            }
        }
        private global::System.String _name_bimar;
        partial void Onname_bimarChanging(global::System.String value);
        partial void Onname_bimarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mellicode_bimar
        {
            get
            {
                return _mellicode_bimar;
            }
            set
            {
                Onmellicode_bimarChanging(value);
                ReportPropertyChanging("mellicode_bimar");
                _mellicode_bimar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mellicode_bimar");
                Onmellicode_bimarChanged();
            }
        }
        private global::System.String _mellicode_bimar;
        partial void Onmellicode_bimarChanging(global::System.String value);
        partial void Onmellicode_bimarChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_Noskhe_Bimar", "Noskhe")]
        public EntityCollection<Noskhe> Noskhe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Noskhe>("DaroKhaneModel.FK_Noskhe_Bimar", "Noskhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Noskhe>("DaroKhaneModel.FK_Noskhe_Bimar", "Noskhe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="Bimeh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bimeh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bimeh object.
        /// </summary>
        /// <param name="code_bimeh">Initial value of the code_bimeh property.</param>
        public static Bimeh CreateBimeh(global::System.Int32 code_bimeh)
        {
            Bimeh bimeh = new Bimeh();
            bimeh.code_bimeh = code_bimeh;
            return bimeh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_bimeh
        {
            get
            {
                return _code_bimeh;
            }
            set
            {
                if (_code_bimeh != value)
                {
                    Oncode_bimehChanging(value);
                    ReportPropertyChanging("code_bimeh");
                    _code_bimeh = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_bimeh");
                    Oncode_bimehChanged();
                }
            }
        }
        private global::System.Int32 _code_bimeh;
        partial void Oncode_bimehChanging(global::System.Int32 value);
        partial void Oncode_bimehChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nameSazman_bimeh
        {
            get
            {
                return _nameSazman_bimeh;
            }
            set
            {
                OnnameSazman_bimehChanging(value);
                ReportPropertyChanging("nameSazman_bimeh");
                _nameSazman_bimeh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nameSazman_bimeh");
                OnnameSazman_bimehChanged();
            }
        }
        private global::System.String _nameSazman_bimeh;
        partial void OnnameSazman_bimehChanging(global::System.String value);
        partial void OnnameSazman_bimehChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String darsad_bimeh
        {
            get
            {
                return _darsad_bimeh;
            }
            set
            {
                Ondarsad_bimehChanging(value);
                ReportPropertyChanging("darsad_bimeh");
                _darsad_bimeh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("darsad_bimeh");
                Ondarsad_bimehChanged();
            }
        }
        private global::System.String _darsad_bimeh;
        partial void Ondarsad_bimehChanging(global::System.String value);
        partial void Ondarsad_bimehChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tarikheEtebar_bimeh
        {
            get
            {
                return _tarikheEtebar_bimeh;
            }
            set
            {
                OntarikheEtebar_bimehChanging(value);
                ReportPropertyChanging("tarikheEtebar_bimeh");
                _tarikheEtebar_bimeh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tarikheEtebar_bimeh");
                OntarikheEtebar_bimehChanged();
            }
        }
        private global::System.String _tarikheEtebar_bimeh;
        partial void OntarikheEtebar_bimehChanging(global::System.String value);
        partial void OntarikheEtebar_bimehChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_Noskhe_Bimeh", "Noskhe")]
        public EntityCollection<Noskhe> Noskhe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Noskhe>("DaroKhaneModel.FK_Noskhe_Bimeh", "Noskhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Noskhe>("DaroKhaneModel.FK_Noskhe_Bimeh", "Noskhe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="Daroo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Daroo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Daroo object.
        /// </summary>
        /// <param name="code_daroo">Initial value of the code_daroo property.</param>
        public static Daroo CreateDaroo(global::System.Int32 code_daroo)
        {
            Daroo daroo = new Daroo();
            daroo.code_daroo = code_daroo;
            return daroo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_daroo
        {
            get
            {
                return _code_daroo;
            }
            set
            {
                if (_code_daroo != value)
                {
                    Oncode_darooChanging(value);
                    ReportPropertyChanging("code_daroo");
                    _code_daroo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_daroo");
                    Oncode_darooChanged();
                }
            }
        }
        private global::System.Int32 _code_daroo;
        partial void Oncode_darooChanging(global::System.Int32 value);
        partial void Oncode_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_daroo
        {
            get
            {
                return _name_daroo;
            }
            set
            {
                Onname_darooChanging(value);
                ReportPropertyChanging("name_daroo");
                _name_daroo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_daroo");
                Onname_darooChanged();
            }
        }
        private global::System.String _name_daroo;
        partial void Onname_darooChanging(global::System.String value);
        partial void Onname_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sherkatTolid_daroo
        {
            get
            {
                return _sherkatTolid_daroo;
            }
            set
            {
                OnsherkatTolid_darooChanging(value);
                ReportPropertyChanging("sherkatTolid_daroo");
                _sherkatTolid_daroo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sherkatTolid_daroo");
                OnsherkatTolid_darooChanged();
            }
        }
        private global::System.String _sherkatTolid_daroo;
        partial void OnsherkatTolid_darooChanging(global::System.String value);
        partial void OnsherkatTolid_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tarikhTolid_daroo
        {
            get
            {
                return _tarikhTolid_daroo;
            }
            set
            {
                OntarikhTolid_darooChanging(value);
                ReportPropertyChanging("tarikhTolid_daroo");
                _tarikhTolid_daroo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tarikhTolid_daroo");
                OntarikhTolid_darooChanged();
            }
        }
        private global::System.String _tarikhTolid_daroo;
        partial void OntarikhTolid_darooChanging(global::System.String value);
        partial void OntarikhTolid_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tarikhEngeza_daroo
        {
            get
            {
                return _tarikhEngeza_daroo;
            }
            set
            {
                OntarikhEngeza_darooChanging(value);
                ReportPropertyChanging("tarikhEngeza_daroo");
                _tarikhEngeza_daroo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tarikhEngeza_daroo");
                OntarikhEngeza_darooChanged();
            }
        }
        private global::System.String _tarikhEngeza_daroo;
        partial void OntarikhEngeza_darooChanging(global::System.String value);
        partial void OntarikhEngeza_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gheymat_daroo
        {
            get
            {
                return _gheymat_daroo;
            }
            set
            {
                Ongheymat_darooChanging(value);
                ReportPropertyChanging("gheymat_daroo");
                _gheymat_daroo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gheymat_daroo");
                Ongheymat_darooChanged();
            }
        }
        private global::System.String _gheymat_daroo;
        partial void Ongheymat_darooChanging(global::System.String value);
        partial void Ongheymat_darooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tedadMojod_daroo
        {
            get
            {
                return _tedadMojod_daroo;
            }
            set
            {
                OntedadMojod_darooChanging(value);
                ReportPropertyChanging("tedadMojod_daroo");
                _tedadMojod_daroo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tedadMojod_daroo");
                OntedadMojod_darooChanged();
            }
        }
        private Nullable<global::System.Int32> _tedadMojod_daroo;
        partial void OntedadMojod_darooChanging(Nullable<global::System.Int32> value);
        partial void OntedadMojod_darooChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Daroo", "AghlameNoskhe")]
        public EntityCollection<AghlameNoskhe> AghlameNoskhe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AghlameNoskhe>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "AghlameNoskhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AghlameNoskhe>("DaroKhaneModel.FK_AghlameNoskhe_Daroo", "AghlameNoskhe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="Karbar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Karbar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Karbar object.
        /// </summary>
        /// <param name="code_karbar">Initial value of the code_karbar property.</param>
        public static Karbar CreateKarbar(global::System.Int32 code_karbar)
        {
            Karbar karbar = new Karbar();
            karbar.code_karbar = code_karbar;
            return karbar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_karbar
        {
            get
            {
                return _code_karbar;
            }
            set
            {
                if (_code_karbar != value)
                {
                    Oncode_karbarChanging(value);
                    ReportPropertyChanging("code_karbar");
                    _code_karbar = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_karbar");
                    Oncode_karbarChanged();
                }
            }
        }
        private global::System.Int32 _code_karbar;
        partial void Oncode_karbarChanging(global::System.Int32 value);
        partial void Oncode_karbarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_karbar
        {
            get
            {
                return _name_karbar;
            }
            set
            {
                Onname_karbarChanging(value);
                ReportPropertyChanging("name_karbar");
                _name_karbar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_karbar");
                Onname_karbarChanged();
            }
        }
        private global::System.String _name_karbar;
        partial void Onname_karbarChanging(global::System.String value);
        partial void Onname_karbarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rmazeVorood_karbar
        {
            get
            {
                return _rmazeVorood_karbar;
            }
            set
            {
                OnrmazeVorood_karbarChanging(value);
                ReportPropertyChanging("rmazeVorood_karbar");
                _rmazeVorood_karbar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rmazeVorood_karbar");
                OnrmazeVorood_karbarChanged();
            }
        }
        private global::System.String _rmazeVorood_karbar;
        partial void OnrmazeVorood_karbarChanging(global::System.String value);
        partial void OnrmazeVorood_karbarChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaroKhaneModel", Name="Noskhe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Noskhe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Noskhe object.
        /// </summary>
        /// <param name="code_noskhe">Initial value of the code_noskhe property.</param>
        /// <param name="code_bimar">Initial value of the code_bimar property.</param>
        /// <param name="code_bimeh">Initial value of the code_bimeh property.</param>
        public static Noskhe CreateNoskhe(global::System.Int32 code_noskhe, global::System.Int32 code_bimar, global::System.Int32 code_bimeh)
        {
            Noskhe noskhe = new Noskhe();
            noskhe.code_noskhe = code_noskhe;
            noskhe.code_bimar = code_bimar;
            noskhe.code_bimeh = code_bimeh;
            return noskhe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_noskhe
        {
            get
            {
                return _code_noskhe;
            }
            set
            {
                if (_code_noskhe != value)
                {
                    Oncode_noskheChanging(value);
                    ReportPropertyChanging("code_noskhe");
                    _code_noskhe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("code_noskhe");
                    Oncode_noskheChanged();
                }
            }
        }
        private global::System.Int32 _code_noskhe;
        partial void Oncode_noskheChanging(global::System.Int32 value);
        partial void Oncode_noskheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_bimar
        {
            get
            {
                return _code_bimar;
            }
            set
            {
                Oncode_bimarChanging(value);
                ReportPropertyChanging("code_bimar");
                _code_bimar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("code_bimar");
                Oncode_bimarChanged();
            }
        }
        private global::System.Int32 _code_bimar;
        partial void Oncode_bimarChanging(global::System.Int32 value);
        partial void Oncode_bimarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 code_bimeh
        {
            get
            {
                return _code_bimeh;
            }
            set
            {
                Oncode_bimehChanging(value);
                ReportPropertyChanging("code_bimeh");
                _code_bimeh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("code_bimeh");
                Oncode_bimehChanged();
            }
        }
        private global::System.Int32 _code_bimeh;
        partial void Oncode_bimehChanging(global::System.Int32 value);
        partial void Oncode_bimehChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_AghlameNoskhe_Noskhe", "AghlameNoskhe")]
        public EntityCollection<AghlameNoskhe> AghlameNoskhe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AghlameNoskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "AghlameNoskhe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AghlameNoskhe>("DaroKhaneModel.FK_AghlameNoskhe_Noskhe", "AghlameNoskhe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_Noskhe_Bimar", "Bimar")]
        public Bimar Bimar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimar>("DaroKhaneModel.FK_Noskhe_Bimar", "Bimar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimar>("DaroKhaneModel.FK_Noskhe_Bimar", "Bimar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bimar> BimarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimar>("DaroKhaneModel.FK_Noskhe_Bimar", "Bimar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bimar>("DaroKhaneModel.FK_Noskhe_Bimar", "Bimar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DaroKhaneModel", "FK_Noskhe_Bimeh", "Bimeh")]
        public Bimeh Bimeh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimeh>("DaroKhaneModel.FK_Noskhe_Bimeh", "Bimeh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimeh>("DaroKhaneModel.FK_Noskhe_Bimeh", "Bimeh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bimeh> BimehReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bimeh>("DaroKhaneModel.FK_Noskhe_Bimeh", "Bimeh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bimeh>("DaroKhaneModel.FK_Noskhe_Bimeh", "Bimeh", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
